GET http://localhost:3000/getUsers

###

# GET http://localhost:3000


POST http://localhost:3000/register
content-type: application/json

{

    "email": "test16@example.com",
    "password": "securepassword",
    "favouriteLocations": [

    ]
}

###
POST http://localhost:3000/register
content-type: application/json

{

    "email": "test16@example.com",
    "password": "securepassword",
    "favouriteLocations": [

    ]
}

###

POST http://localhost:3000/login
content-type: application/json

{

    "email": "test16@example.com",
    "password": "securepassword",
    "favouriteLocations": [

    ]
}

# Hamza!234
###
GET http://localhost:3000/favouriteLocations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njc1ODBkMDFkOWE0Y2FhZmQ2ZmJjNmQiLCJpYXQiOjE3MTg5NzY3MzEsImV4cCI6MTcxODk4MDMzMX0.qtFt4hlqR8S6OeqqsR1_sU8YjlS4srXjSbh0o7fq88s

###
POST http://localhost:3000/register
Content-Type: application/json

{
    "email": "testuser@example.com",
    "password": "securepassword"
}
###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "testuser@example.com",
    "password": "securepassword"
}