GET http://localhost:3000/getUsers

###

# GET http://localhost:3000


POST http://localhost:3000/register
content-type: application/json

{

    "email": "test16@example.com",
    "password": "securepassword",
    "favouriteLocations": [

    ]
}

###
POST http://localhost:3000/register
content-type: application/json

{

    "email": "test16@example.com",
    "password": "securepassword",
    "favouriteLocations": [

    ]
}

###

POST http://localhost:3000/login
content-type: application/json

{

    "email": "test16@example.com",
    "password": "securepassword",
    "favouriteLocations": [

    ]
}

# Hamza!234
###
GET http://localhost:3000/favouriteLocations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njc1OTNiODdjZGE2MDg2N2FhMmJhZDgiLCJpYXQiOjE3MTg5ODE1NjIsImV4cCI6MTcxOTA2Nzk2Mn0.jGSx7hQbZxs7gcI4SqOvt-OeD1-rlQMKOUfITSA62x4

###
POST http://127.0.0.1:3000/favouriteLocations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njc1OTNiODdjZGE2MDg2N2FhMmJhZDgiLCJpYXQiOjE3MTg5ODE1NjIsImV4cCI6MTcxOTA2Nzk2Mn0.jGSx7hQbZxs7gcI4SqOvt-OeD1-rlQMKOUfITSA62x4
Content-Type: application/json

{
    "location": "New York"
}

###
DELETE http://localhost:3000/favouriteLocations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njc1OTNiODdjZGE2MDg2N2FhMmJhZDgiLCJpYXQiOjE3MTg5ODE1NjIsImV4cCI6MTcxOTA2Nzk2Mn0.jGSx7hQbZxs7gcI4SqOvt-OeD1-rlQMKOUfITSA62x4
Content-Type: application/json

{
    "location": "New York"
}

###
POST http://localhost:3000/register
Content-Type: application/json

{
    "email": "testuser@example.com",
    "password": "securepassword"
}
###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "testuser@example.com",
    "password": "securepassword"
}